<?php

namespace ContainerZm9QxQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qm72x9HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qm72x9H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qm72x9H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'post' => ['privates', '.errored..service_locator.qm72x9H.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.qm72x9H": it needs an instance of "App\\Entity\\Post" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
