<?php

namespace ContainerZm9QxQv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qm72x9H.App\Entity\Post' shared service.
     *
     * @return \App\Entity\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qm72x9H": it needs an instance of "App\\Entity\\Post" but this type has been excluded in "config/services.yaml".');
    }
}
