<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_commentaire_getcommentsforpost' => [['post'], ['_controller' => 'App\\Controller\\CommentaireController::getCommentsForPost'], [], [['variable', '/', '[^/]++', 'post', true], ['text', '/api/commentaires']], [], [], []],
    'app_commentaire_updatecommentaire' => [[], ['_controller' => 'App\\Controller\\CommentaireController::updateCommentaire'], [], [['text', '/api/commentaires']], [], [], []],
    'app_commentaire_deletecommentaire' => [['id'], ['_controller' => 'App\\Controller\\CommentaireController::deleteCommentaire'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/commentaires']], [], [], []],
    'app_commentaire_getcomments' => [[], ['_controller' => 'App\\Controller\\CommentaireController::getComments'], [], [['text', '/api/commentaires']], [], [], []],
    'app_commentaire_createcommentaire' => [['post'], ['_controller' => 'App\\Controller\\CommentaireController::createCommentaire'], [], [['variable', '/', '[^/]++', 'post', true], ['text', '/api/commentaires']], [], [], []],
    'app_commentaire_addlike' => [['commentaireId'], ['_controller' => 'App\\Controller\\CommentaireController::addLike'], [], [['variable', '/', '[^/]++', 'commentaireId', true], ['text', '/api/commentaire/like']], [], [], []],
    'app_commentaire_adddislike' => [['commentaireId'], ['_controller' => 'App\\Controller\\CommentaireController::addDislike'], [], [['variable', '/', '[^/]++', 'commentaireId', true], ['text', '/api/commentaire/dislike']], [], [], []],
    'app_commentaire_getpostidbycommentaireid' => [['commentaireId'], ['_controller' => 'App\\Controller\\CommentaireController::getPostIdByCommentaireId'], [], [['variable', '/', '[^/]++', 'commentaireId', true], ['text', '/api/posts/id']], [], [], []],
    'app_commentaire_createreponse' => [['commentaireId'], ['_controller' => 'App\\Controller\\CommentaireController::createReponse'], [], [['variable', '/', '[^/]++', 'commentaireId', true], ['text', '/api/reponse']], [], [], []],
    'app_post_getpostbypostname' => [['username'], ['_controller' => 'App\\Controller\\PostController::getPostByPostname'], [], [['variable', '/', '[^/]++', 'username', true], ['text', '/api/filtre']], [], [], []],
    'app_post_getpostbyid' => [['id'], ['_controller' => 'App\\Controller\\PostController::getPostById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/posts']], [], [], []],
    'app_post_createpost' => [[], ['_controller' => 'App\\Controller\\PostController::createPost'], [], [['text', '/api/posts']], [], [], []],
    'app_post_deletepost' => [['id'], ['_controller' => 'App\\Controller\\PostController::deletePost'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/posts']], [], [], []],
    'app_post_getallposts' => [[], ['_controller' => 'App\\Controller\\PostController::getAllPosts'], [], [['text', '/api/posts']], [], [], []],
    'app_post_getlikecount' => [['postid'], ['_controller' => 'App\\Controller\\PostController::getLikeCount'], [], [['text', '/like'], ['variable', '/', '[^/]++', 'postid', true], ['text', '/api/posts']], [], [], []],
    'app_post_addlike' => [['postId'], ['_controller' => 'App\\Controller\\PostController::addLike'], [], [['variable', '/', '[^/]++', 'postId', true], ['text', '/api/posts/like']], [], [], []],
    'app_post_adddislike' => [['postId'], ['_controller' => 'App\\Controller\\PostController::addDislike'], [], [['variable', '/', '[^/]++', 'postId', true], ['text', '/api/posts/dislike']], [], [], []],
    'app_post_getusernamebypostid' => [['postId'], ['_controller' => 'App\\Controller\\PostController::getUsernameByPostId'], [], [['variable', '/', '[^/]++', 'postId', true], ['text', '/api/posts/username']], [], [], []],
    'app_post_updatepost' => [[], ['_controller' => 'App\\Controller\\PostController::updatePost'], [], [['text', '/api/modifier']], [], [], []],
    'app_user_loguser' => [[], ['_controller' => 'App\\Controller\\UserController::logUser'], [], [['text', '/api/login']], [], [], []],
    'app_user_createuser' => [[], ['_controller' => 'App\\Controller\\UserController::createUser'], [], [['text', '/api/inscription']], [], [], []],
    'app_user_getutilisateur' => [[], ['_controller' => 'App\\Controller\\UserController::getUtilisateur'], [], [['text', '/api/myself']], [], [], []],
    'app_user_getallusers' => [[], ['_controller' => 'App\\Controller\\UserController::getAllUsers'], [], [['text', '/api/users']], [], [], []],
    'app_user_getuserbyusername' => [['username'], ['_controller' => 'App\\Controller\\UserController::getUserByUsername'], [], [['variable', '/', '[^/]++', 'username', true], ['text', '/api/users']], [], [], []],
    'app_user_setban' => [['username'], ['_controller' => 'App\\Controller\\UserController::setBan'], [], [['variable', '/', '[^/]++', 'username', true], ['text', '/api/ban']], [], [], []],
    'app_user_changermdp' => [[], ['_controller' => 'App\\Controller\\UserController::changerMdp'], [], [['text', '/api/changerMdp']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
];
